// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCosAlNlMffhOKcBU8DXyqM6NXxpZgdsbs',
    appId: '1:916503372067:web:d3d59a106810d8b1ff2c96',
    messagingSenderId: '916503372067',
    projectId: 'finance-flow-4ecf2',
    authDomain: 'finance-flow-4ecf2.firebaseapp.com',
    storageBucket: 'finance-flow-4ecf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkXdnCPb1MZ4f42K4IdNYxIfJvUnxYaxo',
    appId: '1:916503372067:android:0e837007f187cc36ff2c96',
    messagingSenderId: '916503372067',
    projectId: 'finance-flow-4ecf2',
    storageBucket: 'finance-flow-4ecf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQ7GlFQaKAtn6YpejjbuNSN_GH7fSwfg',
    appId: '1:916503372067:ios:8e217e618f7955afff2c96',
    messagingSenderId: '916503372067',
    projectId: 'finance-flow-4ecf2',
    storageBucket: 'finance-flow-4ecf2.appspot.com',
    iosBundleId: 'com.example.financeFlowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyQ7GlFQaKAtn6YpejjbuNSN_GH7fSwfg',
    appId: '1:916503372067:ios:8e217e618f7955afff2c96',
    messagingSenderId: '916503372067',
    projectId: 'finance-flow-4ecf2',
    storageBucket: 'finance-flow-4ecf2.appspot.com',
    iosBundleId: 'com.example.financeFlowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCosAlNlMffhOKcBU8DXyqM6NXxpZgdsbs',
    appId: '1:916503372067:web:db6533abf55d8e0dff2c96',
    messagingSenderId: '916503372067',
    projectId: 'finance-flow-4ecf2',
    authDomain: 'finance-flow-4ecf2.firebaseapp.com',
    storageBucket: 'finance-flow-4ecf2.appspot.com',
  );
}
